id = "serendipity"
name = "Serendipity Themes"
schema_version = 1
version = "0.0.4"
authors = ["Nguyen Dang Vinh <meocoder@gmail.com>"]
description = "Relaxed, gentle and modern | Serendipity theme for Zed"
repository = "https://github.com/meocoder31099/Serendipity-Theme-Zed"